"""
app/themes.py — "What Matters Now" scoring and selection.

Scores each StoryCluster on a composite scale that heavily weights cross-asset
importance, recency, and multi-source confirmation.  Single-stock or single-
sector stories with no broader market implications score lower than macro,
geopolitical, or multi-asset themes even if their signal_strength is high.
"""

from __future__ import annotations

import math
import logging
import re
from datetime import datetime, timezone

from app.clustering import StoryCluster, WhatMattersNowItem
from app.model      import Message, get_client

log = logging.getLogger(__name__)

# ── LLM label cache ────────────────────────────────────────────────────────────
# cluster.id → 2–4 word theme label generated by LLM
_LABEL_CACHE: dict[str, str] = {}

_LABEL_SYSTEM = """\
You are a financial editor writing concise market theme labels for an institutional investment dashboard.

Given a news headline and optionally its market implication, output EXACTLY ONE label of 2–4 words that names the UNDERLYING MARKET THEME OR FORCE — not the company, not the article title, not a person's name.

Ask yourself: what specific market dynamic, instrument, or risk does this story represent?

GOOD → BAD contrasts (always prefer the GOOD column):
  "Australian miner Fenix cuts iron ore output"   → Iron Ore Supply Risk      (NOT "Australian Ore Miner Fenix")
  "IFM Investors CEO steps down"                  → Private Markets Outlook   (NOT "IFM Investors CEO")
  "Fed signals no rush to cut rates"              → Rate Cut Delay            (NOT "Fed Chair Powell")
  "TSMC raises AI capex guidance"                 → AI Capex Cycle            (NOT "TSMC Capex Guidance")
  "China restricts rare earth exports"            → Rare Earth Supply Risk    (NOT "China Rare Earth")
  "Oil spikes on Middle East escalation"          → Oil Supply Disruption     (NOT "Risk Pressure")
  "Treasury yields hit 5% on inflation data"      → Yield Surge Risk          (NOT "Market Concern")
  "Credit spreads widen as growth fears mount"    → Credit Spread Widening    (NOT "Economic Uncertainty")
  "Tariffs threat lifts dollar, hurts EM bonds"   → Tariff Dollar Squeeze     (NOT "Trade Risk")

Rules:
- 2 to 4 words only. Title case. No punctuation, no ellipsis.
- Be SPECIFIC: name the instrument, asset class, or region — "Yield Curve Steepening" not "Rate Risk"; "EM Currency Pressure" not "Market Risk".
- Name the force, risk, or dynamic — never the ticker or person.
- NEVER output generic labels: "Risk Pressure", "Market Risk", "Economic Uncertainty", "Market Concern", "Market Volatility" alone.
- Avoid action verbs ("surges", "rises", "falls"). Prefer specific nouns: Supply Risk, Spread Widening, Demand Slowdown, Contagion, Pivot, Squeeze, Disruption.
- Only include a company name if it IS the theme (e.g. "Apple Buyback Program" for an Apple-specific capital return story with no broader implication).
- Output the label only. No explanation, no quotes.\
"""

# Broad market dynamics used in fallback labels
_FALLBACK_DYNAMICS: dict[str, str] = {
    "Geopolitical": "Geopolitical Risk",
    "Markets":      "Market Volatility",
    "M&A":          "Deal Activity",
    "Company":      "Corporate Development",
}


# ── Scoring weights ────────────────────────────────────────────────────────────

_CAT_WEIGHT: dict[str, float] = {
    "Geopolitical": 1.25,
    "Markets":      1.15,
    "M&A":          1.20,
    "Company":      0.85,
}
_STR_WEIGHT: dict[str, float] = {
    "strong": 1.00,
    "medium": 0.55,
    "weak":   0.15,
}

# Entities associated with specific asset classes (for cross-asset detection)
_BROAD: frozenset[str] = frozenset({
    "USD", "EUR", "GBP", "JPY", "S&P", "SPX", "Nasdaq", "Dow",
    "Fed", "FOMC", "ECB", "BoJ", "Markets", "Equities",
})
_FX:         frozenset[str] = frozenset({"USD", "EUR", "JPY", "GBP", "CNY", "FX", "Dollar", "Yen", "Euro", "DXY"})
_RATES:      frozenset[str] = frozenset({"Treasury", "Treasuries", "Bonds", "Yields", "Fed", "FOMC", "Rates", "10Y", "2Y", "30Y"})
_COMMODITIES: frozenset[str] = frozenset({"Oil", "WTI", "Brent", "Gold", "Silver", "Copper", "Commodities", "CL", "GC", "NG"})


# ── Public API ─────────────────────────────────────────────────────────────────

def select_what_matters_now(
    clusters: list[StoryCluster],
    n: int = 5,
    now: datetime | None = None,
) -> list[WhatMattersNowItem]:
    """
    Score all clusters, sort descending, return the top-n as WhatMattersNowItems.
    Mutates cluster.cluster_score in-place for downstream use by the API layer.

    Duplicate-label guard: if two clusters would produce the same wmn_label (e.g.
    both fall back to "Market Volatility" when the LLM is unavailable), the lower-
    ranked duplicate is skipped and the next distinct cluster is used instead.
    This prevents visually identical cards in the What Matters Now row.
    """
    if not clusters:
        return []

    if now is None:
        now = datetime.now(timezone.utc)

    scored: list[tuple[float, StoryCluster]] = [
        (score_cluster(c, now), c) for c in clusters
    ]
    scored.sort(key=lambda x: x[0], reverse=True)

    result:      list[WhatMattersNowItem] = []
    seen_labels: set[str]                 = set()
    rank = 1

    for s, cluster in scored:
        if len(result) >= n:
            break
        cluster.cluster_score = round(s, 4)
        label = _generate_wmn_label(cluster)
        if label in seen_labels:
            log.debug("[wmn] skipping duplicate label %r (cluster %s)", label, cluster.id)
            continue
        seen_labels.add(label)
        result.append(WhatMattersNowItem(
            rank=rank,
            cluster=cluster,
            reason=_make_reason(cluster),
            thesis=_make_thesis(cluster),
            wmn_label=label,
        ))
        rank += 1

    return result


def score_cluster(cluster: StoryCluster, now: datetime | None = None) -> float:
    """
    Composite score (0–∞, not bounded at 1.0).

    Components:
      recency     — exponential decay with 3-hour half-life
      strength    — signal_strength mapped to weight
      score_norm  — signal_score / 100
      cross       — cross-asset breadth multiplier (0.45–1.0)
      cat         — category importance weight
      size_bonus  — multi-source confirmation bonus
    """
    if now is None:
        now = datetime.now(timezone.utc)
    p = cluster.primary

    # 1. Recency — half-life varies by signal strength so breaking strong-signal
    # stories (major M&A, Fed decisions) stay prominent for longer than opinion pieces.
    sig = getattr(p, "signal_strength", "medium")
    half_life = 6.0 if sig == "strong" else 3.0 if sig == "medium" else 2.0
    if getattr(p, "published_dt", None):
        age_h   = (now - p.published_dt).total_seconds() / 3600
        recency = math.exp(-age_h / half_life)
    else:
        recency = 0.08  # no timestamp → heavily deprioritised

    # 2. Signal
    strength = _STR_WEIGHT.get(getattr(p, "signal_strength", "medium"), 0.55)
    score_n  = min(max(getattr(p, "signal_score", 0.0), 0.0) / 100.0, 1.0)

    # 3. Cross-asset (dominant differentiator)
    cross = _cross_asset_score(cluster)

    # 4. Category
    cat = _CAT_WEIGHT.get(getattr(p, "category", ""), 1.0)

    # 5. Cluster size bonus (each extra story = +15%, capped at 4 extras)
    size_bonus = 1.0 + 0.15 * min(cluster.story_count - 1, 4)

    # Cross-asset weighted heavily: a macro story with cross=0.8 outscores
    # a single-stock strong-signal story with cross=0.1 even at equal recency.
    base = recency * strength * score_n * cat * size_bonus * (0.45 + 0.55 * cross)

    # Relevance filter: heavily penalise single-company medium/weak stories
    # that don't justify a "What Matters Now" slot.
    if (
        cluster.story_count == 1
        and getattr(p, "category", "") == "Company"
        and getattr(p, "signal_strength", "medium") in ("medium", "weak")
    ):
        base *= 0.30

    # Consumer noise penalty: down-weight clusters driven by consumer/personal-
    # finance content so they never surface in What Matters Now.  Uses the
    # consumer_noise_penalty field set by score_item() — a 30-pt penalty maps
    # to a 0.50 multiplier (graceful, not binary).
    consumer_penalty = getattr(p, "consumer_noise_penalty", 0.0)
    if consumer_penalty > 0:
        base *= max(0.10, 1.0 - consumer_penalty / 60.0)

    return base


def _cross_asset_score(cluster: StoryCluster) -> float:
    """Return 0–1 reflecting how broadly the theme spans asset classes."""
    p = cluster.primary
    score = 0.0

    # Category-level base score
    cat = getattr(p, "category", "")
    if cat == "Geopolitical":
        score += 0.55   # wars, sanctions, elections → everything moves
    elif cat == "Markets":
        score += 0.40   # broad market news
    elif cat == "M&A":
        score += 0.20   # deal can ripple across sectors
    # Company defaults to 0 — needs entity breadth to lift score

    # Count distinct asset classes — check both extracted entities AND title text
    # so stories like "Dollar slides as yields fall" get full cross-asset credit
    # even when the entity extractor missed the asset-class tokens.
    asset_types: set[str] = set()
    for e in getattr(p, "affected_entities", []):
        if e in _FX:
            asset_types.add("fx")
        elif e in _RATES:
            asset_types.add("rates")
        elif e in _COMMODITIES:
            asset_types.add("commodities")
        elif e.startswith("$") or (len(e) <= 5 and e.isupper() and e not in _BROAD):
            asset_types.add("equity")

    title_lower = (getattr(p, "title", "") or "").lower()
    if "fx" not in asset_types and re.search(
        r"\b(dollar|yen|yuan|euro|sterling|pound|fx|currency|forex|dxy|usdx)\b", title_lower
    ):
        asset_types.add("fx")
    if "rates" not in asset_types and re.search(
        r"\b(yield|yields|rate\s+hike|rate\s+cut|bond|treasury|bund|gilt|duration|credit\s+spread)\b",
        title_lower,
    ):
        asset_types.add("rates")
    if "commodities" not in asset_types and re.search(
        r"\b(oil|brent|wti|crude|gold|silver|copper|gas|commodity|commodities|wheat|corn)\b",
        title_lower,
    ):
        asset_types.add("commodities")
    if "equity" not in asset_types and re.search(
        r"\b(stock|stocks|equit|nasdaq|s&p|dow|shares|sharemarket|index|indices|earnings)\b",
        title_lower,
    ):
        asset_types.add("equity")

    score += min(len(asset_types) * 0.15, 0.30)

    # Mixed-category cluster = confirmed multi-asset spillover (e.g. tariff story
    # causes both Company and Geopolitical coverage)
    if cluster.related:
        cats = {cat} | {getattr(r, "category", "") for r in cluster.related}
        if len(cats) > 1:
            score += 0.15

    return min(score, 1.0)


def _generate_wmn_label(cluster: StoryCluster) -> str:
    """
    Generate a 2–4 word market theme label via LLM, cached by cluster.id.

    Falls back to _fallback_wmn_label() — a category/asset-aware heuristic —
    rather than cluster.theme_label (which can produce article fragments).
    """
    if cluster.id in _LABEL_CACHE:
        return _LABEL_CACHE[cluster.id]

    p     = cluster.primary
    title = getattr(p, "title", "").strip()
    why   = getattr(p, "why_it_matters", "").strip()

    if title:
        prompt = f"Headline: {title}"
        if why:
            prompt += f"\nMarket implication: {why}"
        try:
            client   = get_client()
            messages = [Message.system(_LABEL_SYSTEM), Message.user(prompt)]
            raw      = "".join(client.chat(messages, stream=True, temperature=0.1)).strip()

            label = raw.splitlines()[0].strip().strip('"\'')
            words = label.split()
            if 2 <= len(words) <= 4 and _is_valid_wmn_label(label):
                _LABEL_CACHE[cluster.id] = label
                return label

            log.debug("[wmn_label] rejected LLM output: %r (%d words)", label, len(words))
        except Exception as exc:
            log.debug("[wmn_label] LLM call failed: %s", exc)

    label = _fallback_wmn_label(cluster)
    _LABEL_CACHE[cluster.id] = label
    return label


def _is_valid_wmn_label(label: str) -> bool:
    """
    Return False if the label looks like an article fragment or person/company name
    rather than a market theme.
    """
    # Reject ellipsis — truncated title fragment
    if "…" in label or "..." in label:
        return False
    # Reject labels ending in a person role suffix (CEO, CFO, etc.)
    if re.search(r"\b(CEO|CFO|CTO|COO|Chairman|President|Director|Head)\b", label, re.I):
        return False
    # Reject if it reads like "Company Verb" (e.g. "NVDA Surges", "Apple Rises")
    if re.search(r"\b(surges?|rises?|falls?|drops?|jumps?|slides?|gains?|declines?)\b", label, re.I):
        return False
    return True


def _fallback_wmn_label(cluster: StoryCluster) -> str:
    """
    Category/asset-aware heuristic fallback — produces a clean market-facing label
    without relying on the LLM when it is unavailable.

    For Markets clusters the generic "Market Volatility" is used only as a last
    resort. We first try to derive a specific label from the primary story's
    entities and title nouns, producing labels like "Yield Surge", "Oil Pressure",
    or "Dollar Shift" that distinguish otherwise similar clusters.
    """
    p   = cluster.primary
    cat = getattr(p, "category", "")

    # Priority 1: asset-class entity (rates/FX/commodities) paired with a
    # financial noun from the title — most specific possible fallback.
    asset_ents = [
        e for e in getattr(p, "affected_entities", [])
        if e in (_FX | _RATES | _COMMODITIES)
    ]
    lead_asset = asset_ents[0] if asset_ents else ""

    title_lower = (getattr(p, "title", "") or "").lower()
    noun = ""
    for candidate in ("Surge", "Rally", "Selloff", "Crash", "Correction",
                       "Risk", "Outlook", "Demand", "Supply", "Pressure",
                       "Contagion", "Crisis", "Pivot", "Shift", "Volatility",
                       "Default", "Inflation", "Tariff", "Sanctions", "Squeeze",
                       "Widening", "Tightening", "Reversal", "Breakout"):
        if candidate.lower() in title_lower:
            noun = candidate
            break

    if lead_asset and noun:
        return f"{lead_asset} {noun}"
    if lead_asset and cat:
        return f"{lead_asset} {_FALLBACK_DYNAMICS.get(cat, cat)}"
    if noun and cat:
        return f"{cat} {noun}"

    # Priority 2: for Markets clusters, try to extract a leading subject noun
    # from the title (oil/stocks/yields etc.) so sibling Markets clusters get
    # distinct labels rather than all landing on "Market Volatility".
    if cat == "Markets":
        _MARKET_SUBJECTS = [
            ("oil", "Oil Move"), ("brent", "Oil Move"), ("crude", "Oil Move"),
            ("gold", "Gold Move"), ("copper", "Copper Move"),
            ("bitcoin", "Crypto Move"), ("crypto", "Crypto Move"),
            ("yield", "Yield Move"), ("treasury", "Treasury Move"),
            ("bond", "Bond Move"), ("dollar", "Dollar Move"),
            ("nasdaq", "Nasdaq Move"), ("s&p", "Equity Move"),
            ("stock", "Equity Move"), ("equit", "Equity Move"),
        ]
        for keyword, label in _MARKET_SUBJECTS:
            if keyword in title_lower:
                return label
        # Only use the generic fallback when no subject can be identified
        return "Market Volatility"

    return _FALLBACK_DYNAMICS.get(cat, "Market Development")


def _make_thesis(cluster: StoryCluster) -> str:
    """
    Return a 1-sentence interpretation of why this matters for markets.

    Priority:
      1. why_it_matters — LLM-written investment implication (most interpretive).
      2. First sentence of AI summary — factual fallback.
      3. Template fallback using category + affected entities.
    """
    p = cluster.primary

    # ── Try why_it_matters first (investment implication) ─────────────────────
    why = getattr(p, "why_it_matters", "").strip()
    if why and len(why) >= 20:
        return why[:180]

    # ── Try AI summary first sentence ─────────────────────────────────────────
    summary = getattr(p, "summary", "").strip()
    if summary:
        # Extract first sentence (ends with . ! or ?)
        m = re.match(r"^(.+?[.!?])\s", summary)
        if m:
            sentence = m.group(1).strip()
            if len(sentence) >= 25:
                return sentence[:180]
        # No punctuation boundary found — use the whole summary up to 180 chars
        if len(summary) >= 25:
            truncated = summary[:180]
            # Don't end mid-word
            if len(summary) > 180:
                truncated = truncated.rsplit(" ", 1)[0] + "…"
            return truncated

    # ── Template fallback ──────────────────────────────────────────────────────
    ents = [e for e in getattr(p, "affected_entities", []) if e not in _BROAD][:2]
    cat  = getattr(p, "category", "")
    ent_str = " and ".join(ents) if ents else ""

    if cat == "Geopolitical":
        return (
            f"{ent_str} tensions drive risk-off flows, pressuring equities and lifting safe-haven demand." if ent_str
            else "Geopolitical escalation drives risk-off positioning — safe havens bid, risk assets pressured."
        )
    if cat == "M&A":
        return (
            f"Deal activity in {ent_str} signals sector re-rating and forces multiple repricing across peers." if ent_str
            else "M&A signals sector re-rating — forces multiple repricing and lifts strategic premium expectations."
        )
    if cat == "Markets":
        return (
            f"Broad {ent_str} moves reflect macro repricing — triggers positioning shifts across asset classes." if ent_str
            else "Macro repricing drives cross-asset positioning shifts — risk appetite and credit spreads in focus."
        )
    if ent_str:
        return f"Developments at {ent_str} trigger sector repricing and pressure related exposures."
    return "Cross-asset theme driving positioning shifts — monitor for macro spillover."


def _make_reason(cluster: StoryCluster) -> str:
    """Brief human-readable label for why this theme ranks highly."""
    parts: list[str] = []
    if cluster.story_count > 1:
        parts.append(f"{cluster.story_count} stories")
    if getattr(cluster.primary, "signal_strength", "") == "strong":
        parts.append("strong signal")
    ents = [e for e in getattr(cluster.primary, "affected_entities", []) if e not in _BROAD][:2]
    if ents:
        parts.append(" · ".join(ents))
    elif getattr(cluster.primary, "category", ""):
        parts.append(cluster.primary.category)
    return " · ".join(parts) if parts else "Market update"
